echo "print all ENV VARIABLES defined with the PBS job"
echo "PBS_O_HOME" $PBS_O_HOME
echo "PBS_O_LANG" $PBS_O_LANG
echo "PBS_O_LOGNAME" $PBS_O_LOGNAME
echo "PBS_O_PATH" $PBS_O_PATH
echo "PBS_O_MAIL" $PBS_O_MAIL
echo "PBS_O_SHELL" $PBS_O_SHELL
echo "PBS_O_TZ" $PBS_O_TZ
echo "PBS_O_HOST" $PBS_O_HOST
echo "PBS_SERVER" $PBS_SERVER
echo "PBS_O_QUEUE" $PBS_O_QUEUE
echo "PBS_O_WORKDIR" $PBS_O_WORKDIR
echo "PBS_ARRAYID" $PBS_ARRAYID
echo "PBS_ENVIRONMENT" $PBS_ENVIRONMENT
echo "PBS_GPUFILE" $PBS_GPUFILE
while read line; do echo $line; done < $PBS_GPUFILE
echo "PBS_JOBID" $PBS_JOBID
echo "PBS_JOBNAME" $PBS_JOBNAME
echo "PBS_NODEFILE" $PBS_NODEFILE
while read line; do echo $line; done < $PBS_NODEFILE
echo "PBS_QUEUE" $PBS_QUEUE
