name: pytorch_base
channels:
  - conda-forge
dependencies:
  - pytorch
  # make sure that pytorch with CUDA support is installed
  - pytorch-gpu
  - torchvision
  - torchaudio
  # If you have a required CUDA version, uncomment and specify the version
  # - cuda-version=12.6
  - numpy
